### PR TITLE
Fixed invoice, expiration, and current time error

### LINKED ISSUE #174: Invoice timestamps are too far in the future
When making a call to $client->createInvoice(), I'm seeing creationTime and expirationTime as timestamps far off into the future. The bitpay client is incorrectly treating timestamps returned by the API as seconds instead of milliseconds.

### PR DESCRIPTION
**Pull request by kleetus**
Fixes #174 
- client was trying to create objects from unix timestamps with millisecond resolution
- added a test to ensure these time-based objects are always in the past

### CODE REVIEW

**Comment by braydonf** [comment]
LGTM

**Comment by leonar15** [comment]
Just a tip, but this doesn't seem like a good solution. The issue is that the API is returning milliseconds since the Unix epoch, but it's much more common to use seconds instead. Also, this would differ from other classes in your SDK that expect the timestamp to be given in seconds.

See \Bitpay\Client\Client() line 554
https://github.com/bitpay/php-bitpay-client/blob/master/src/Bitpay/Client/Client.php#L554

**Comment by kleetus** [comment]
I am not sure I catch your meaning. Feel free to post a merge request against my branch to show me what you mean in the code itself. If the issue is that the API should be returning seconds instead of milliseconds, then this would be an issue for another project. In the case of:

https://github.com/bitpay/php-bitpay-client/blob/master/src/Bitpay/Client/Client.php#L554 

If I am not mistaken, the token creation datetime is given as milliseconds since unix epoch from the API. Please let me know what I am missing. thanks

**Comment by leonar15** [comment]
Apologies if I wasn't clear in my prior comment. I'm suggesting that the bitpay Client() class handle the conversion between milliseconds and seconds since it is the intermediary between the local objects and the bitpay API. If you change the API to return seconds (instead of milliseconds) you might break lots of existing integrations. 

Here's the change I made locally to the Client class (https://github.com/bitpay/php-bitpay-client/blob/master/src/Bitpay/Client/Client.php):
```
$invoice
    ->setToken($invoiceToken->setToken($data['token']))
    .... snip......
    ->setInvoiceTime(floor($data['invoiceTime'] / 1000))
    ->setExpirationTime(floor($data['expirationTime'] / 1000))
    ->setCurrentTime(floor($data['currentTime'] / 1000))
    .... snip......
```

**Comment by kleetus** [comment]
I understand where you are coming from. I'll make the changes.

**Pull request merged**
