### PR TITLE
Bug/field types

### LINKED ISSUE #180: Bitpay API returns btcPaid as a string
is_float check returns false, so btcPaid is always 0

[Invoice.php#L680](https://github.com/bitpay/php-bitpay-client/blob/master/src/Bitpay/Invoice.php#L680)

### PR DESCRIPTION
**Pull request by kleetus**
closes #180 

checks api value as numeric (string or not), then casts to float. This should not be a breaking api change.

### CODE REVIEW

**Comment by pnagurny** [comment]
LGTM

**Comment by mindaugas-dt** [comment]
Having problems with downloading a new version with composer. Looks like packagist was not updated. Could you please update it? [packagist: bitpay/php-client](https://packagist.org/packages/bitpay/php-client)

**Comment by kleetus** [comment]
I've updated packagist for v2.2.11, it normally works off the webhook, but not this last time.

**Comment by mindaugas-dt** [comment]
Thanks!

**Pull request merged**
