### PR TITLE
Fixed the problem with prices for some locales

### PR DESCRIPTION
**Pull request by itelmenko**
Some locales have decimal comma instead of dot. But in this case converting from string to float is incorrect:

```
setlocale(LC_NUMERIC, 'ru_RU.UTF-8'); 
$amount = '10.95';
$fAmount = (float) $amount;
var_dump($fAmount);  // result is 10.95
$amount = '10,95';
$fAmount = (float) $amount; 
var_dump($fAmount);  // result is 10
```
I have fixed it.

Also BitPay package works fine for php 5.3.15. I have tested it on production

### CODE REVIEW

**Comment by pieterpoorthuis** [comment]
Rejecting this PR, because it can cause problems with merchants using , as a thousand separator.

**Comment by itelmenko** [comment]
So you have problems with some locales

**Comment by pieterpoorthuis** [comment]
BitPay's PHP library should not replace characters in the price.

Instead, the local implementation of the merchant should reformat the price in such a way that it can be passed to BitPay's PHP library.

**Comment by itelmenko** [comment]
And merchants using comma as a thousand separator? They also do that?
Also where in documentation I can read it?

**Pull request closed without merging**
